PlantSwap/Models/Plant.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PlantSwap.Models
{
  public class Plant
  {
    public Plant()
    {
      this.OfferJoinEntity = new HashSet<Offer>();
      this.RequestJoinEntity = new HashSet<Request>();
    }
    public int PlantId { get; set; }

    public string Genus { get; set; }
    public string Species { get; set; }
    [Required]
    [DisplayName("Common Name")]

    public string CommonName { get; set; }
    public string Variety { get; set; }
    public virtual ICollection<Offer> OfferJoinEntity { get;}
    public virtual ICollection<Request> RequestJoinEntity { get; }
  }
}

PlantSwap/Controllers/PlantsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlantSwap.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PlantSwap.Controllers
{
  [Authorize]
  public class PlantsController : Controller
  {
    private readonly PlantSwapContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public PlantsController(UserManager<ApplicationUser> userManager, PlantSwapContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Plants.OrderBy(x => x.CommonName).ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Plant plant)
    {
      ViewBag.ErrorMessage = "";
      bool isUnique = true;
      List<Plant> plantList = _db.Plants.ToList();
      foreach(Plant iteration in plantList)
      {
        if (plant.CommonName == iteration.CommonName) 
        {
          isUnique = false;
          ModelState.AddModelError("DuplicatePlant", iteration.CommonName + " already exists");
          return View();
        }
      }
      if (isUnique)
      {
        _db.Plants.Add(plant);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Plant thisPlant = _db.Plants
          .Include(plant => plant.OfferJoinEntity)
          .ThenInclude(join => join.Trader)
          .Include(plant => plant.RequestJoinEntity)
          .ThenInclude(join => join.Trader)
          .FirstOrDefault(plant => plant.PlantId == id);
      return View(thisPlant);
    }

    public ActionResult Edit(int id)
    {
      Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == id);
      ViewBag.TraderId = new SelectList(_db.Traders, "TraderId", "TraderName");
      return View(thisPlant);
    }

    [HttpPost]
    public ActionResult Edit(Plant plant, int TraderId)
    {
      if (TraderId != 0)
      {
        _db.Offers.Add(new Offer() {TraderId = TraderId, PlantId = plant.PlantId});
        _db.Requests.Add(new Request() { TraderId = TraderId, PlantId = plant.PlantId });
      }
      _db.Entry(plant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddOffer(int id)
    {
      Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == id);
      ViewBag.Traders = _db.Traders.ToList();
      ViewBag.Plants = _db.Plants.ToList();
      return View(thisPlant);
    }

    [HttpPost]
    public ActionResult AddOffer(Plant plant, int traderId, bool isCutting, DateTime listingDate, int exchangeId, string exchangeCommonName, bool imperfectMatch, int maxDistance)
    {
      if (traderId != 0)
      {
        ViewBag.ErrorMessage = "";
        bool isUnique = true;
        List<Offer> offerList = _db.Offers.ToList();
        foreach(Offer iteration in offerList)
        {
          if (plant.PlantId == iteration.PlantId && traderId == iteration.TraderId) 
          {
            isUnique = false;
            Trader thisTrader = _db.Traders.FirstOrDefault( trader => trader.TraderId == traderId);
            ModelState.AddModelError("DuplicateTrader", "This plant is already offered by " + thisTrader.TraderName);
            Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == traderId);
            ViewBag.Traders = _db.Traders.ToList();
            ViewBag.Plants = _db.Plants.ToList();
            return View(thisPlant);
          }
        }
        if (isUnique)
        {
          _db.Offers.Add(new Offer() { TraderId = traderId, PlantId = plant.PlantId, IsCutting = isCutting, ListingDate = listingDate, WillAcceptPlantId = exchangeId, WillAcceptPlantCommonName = exchangeCommonName,ImperfectMatch = imperfectMatch, MaxDistance = maxDistance });
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult AddRequest(int id)
    {
      Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == id);
      ViewBag.Traders = _db.Traders.ToList();
      ViewBag.Plants = _db.Plants.ToList();
      return View(thisPlant);
    }

    [HttpPost]
    public ActionResult AddRequest(Plant plant, int traderId, DateTime listingDate, int exchangeId, string exchangeCommonName, bool isCutting, int maxDistance)
    {
      if (traderId != 0)
      {
        ViewBag.ErrorMessage = "";
        bool isUnique = true;
        List<Request> requestList = _db.Requests.ToList();
        foreach(Request iteration in requestList)
        {
          if (plant.PlantId == iteration.PlantId && traderId == iteration.TraderId) 
          {
            isUnique = false;
            Trader thisTrader = _db.Traders.FirstOrDefault( trader => trader.TraderId == traderId);
            ModelState.AddModelError("DuplicateTrader", "This plant is already requested by " + thisTrader.TraderName);
            Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == traderId);
            ViewBag.Traders = _db.Traders.ToList();
            ViewBag.Plants = _db.Plants.ToList();
            return View(thisPlant);
          }
        }
        if (isUnique)
        {
          _db.Requests.Add(new Request() { TraderId = traderId, PlantId = plant.PlantId, ListingDate = listingDate, HaveToOfferPlantId = exchangeId, HaveToOfferPlantCommonName = exchangeCommonName, IsCutting = isCutting, MaxDistance = maxDistance });
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == id);
      return View(thisPlant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Plant thisPlant = _db.Plants.FirstOrDefault(plant => plant.PlantId == id);
      _db.Plants.Remove(thisPlant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteOffer(int joinId)
    {
      Offer joinEntry = _db.Offers.FirstOrDefault(entry => entry.OfferId == joinId);
      _db.Offers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  
    [HttpPost]
    public ActionResult DeleteRequest(int joinId)
    {
      Request joinEntry = _db.Requests.FirstOrDefault(entry => entry.RequestId == joinId);
      _db.Requests.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PlantSwap/Controllers/TradersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlantSwap.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PlantSwap.Controllers
{
  [Authorize]
  public class TradersController : Controller
  {
    private readonly PlantSwapContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TradersController(UserManager<ApplicationUser> userManager, PlantSwapContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Traders.OrderBy(x => x.TraderHandle).ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Trader trader)
    {
      ViewBag.ErrorMessage = "";
      bool isUnique = true;
      List<Trader> traderList = _db.Traders.ToList();
      foreach(Trader iteration in traderList)
      {
        if (trader.TraderHandle == iteration.TraderHandle) 
        {
          isUnique = false;
          ModelState.AddModelError("DuplicateTrader", iteration.TraderHandle + " already exists");
          return View();
        }
      }
      if (isUnique)
      {
        _db.Traders.Add(trader);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Trader thisTrader = _db.Traders
          .Include(trader => trader.OfferJoinEntity)
          .ThenInclude(join => join.Plant)
          .Include(trader => trader.RequestJoinEntity)
          .ThenInclude(join => join.Plant)
          .FirstOrDefault(trader => trader.TraderId == id);
      return View(thisTrader);
    }

    public ActionResult Edit(int id)
    {
      Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == id);
      ViewBag.PlantId = new SelectList(_db.Plants, "PlantId", "CommonName");
      return View(thisTrader);
    }

    [HttpPost]
    public ActionResult Edit(Trader trader, int PlantId)
    {
      if (PlantId != 0)
      {
        _db.Offers.Add(new Offer() {TraderId = trader.TraderId, PlantId = PlantId});
        _db.Requests.Add(new Request() { TraderId = trader.TraderId, PlantId = PlantId });
      }
      _db.Entry(trader).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddOffer(int id)
    {
      Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == id);
      ViewBag.Plants = _db.Plants.ToList();
      return View(thisTrader);
    }

    [HttpPost]
    public ActionResult AddOffer(Trader trader, int plantOfferedId, bool isCutting, DateTime listingDate, int exchangeId, string exchangeCommonName, bool imperfectMatch, int maxDistance)
    {
      if (plantOfferedId != 0)
      {
        ViewBag.ErrorMessage = "";
        bool isUnique = true;
        List<Offer> offerList = _db.Offers.ToList();
        foreach(Offer iteration in offerList)
        {
          if (trader.TraderId == iteration.TraderId && plantOfferedId == iteration.PlantId) 
          {
            isUnique = false;
            Plant thisPlant = _db.Plants.FirstOrDefault( plant => plant.PlantId == plantOfferedId);
            ModelState.AddModelError("DuplicatePlant", "This trader is already offering " + thisPlant.CommonName);
            Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == plantOfferedId);
            ViewBag.Plants = _db.Plants.ToList();
            return View(thisTrader);
          }
        }
        if (isUnique)
        {
          _db.Offers.Add(new Offer() { PlantId = plantOfferedId, TraderId = trader.TraderId, IsCutting = isCutting, ListingDate = listingDate, WillAcceptPlantId = exchangeId, WillAcceptPlantCommonName = exchangeCommonName, ImperfectMatch = imperfectMatch, MaxDistance = maxDistance });
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult AddRequest(int id)
    {
      Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == id);
      ViewBag.Plants = _db.Plants.ToList();
      return View(thisTrader);
    }

    [HttpPost]
    public ActionResult AddRequest(Trader trader, int plantRequestedId, DateTime listingDate, int exchangeId, string exchangeCommonName, bool isCutting, int maxDistance)
    {
      if (plantRequestedId != 0)
      {
        ViewBag.ErrorMessage = "";
        bool isUnique = true;
        List<Request> requestList = _db.Requests.ToList();
        foreach(Request iteration in requestList)
        {
          if (trader.TraderId == iteration.TraderId && plantRequestedId == iteration.PlantId) 
          {
            isUnique = false;
            Plant thisPlant = _db.Plants.FirstOrDefault( plant => plant.PlantId == plantRequestedId);
            ModelState.AddModelError("DuplicatePlant", "This trader has already requested " + thisPlant.CommonName);
            Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == plantRequestedId);
            ViewBag.Plants = _db.Plants.ToList();
            return View(thisTrader);
          }
        }
        if (isUnique)
        {
          _db.Requests.Add(new Request() { PlantId = plantRequestedId, TraderId = trader.TraderId, ListingDate = listingDate, HaveToOfferPlantId = exchangeId, HaveToOfferPlantCommonName = exchangeCommonName, IsCutting = isCutting, MaxDistance = maxDistance }
          );
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Trader thisTrader = _db.Traders.FirstOrDefault(trader=> trader.TraderId == id);
      return View(thisTrader);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Trader thisTrader = _db.Traders.FirstOrDefault(trader => trader.TraderId == id);
      _db.Traders.Remove(thisTrader);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteOffer(int joinId)
    {
      Offer joinEntry = _db.Offers.FirstOrDefault(entry => entry.OfferId == joinId);
      _db.Offers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  
    [HttpPost]
    public ActionResult DeleteRequest(int joinId)
    {
      Request joinEntry = _db.Requests.FirstOrDefault(entry => entry.RequestId == joinId);
      _db.Requests.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PlantSwap/Views/Plants/AddOffer.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant

<h2>Add an offer of @Html.DisplayFor(model => model.CommonName)</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
<div class="form-entry">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.PlantId)

    @Html.Label("Select *your* Handle")
    @Html.DropDownList("traderId", new SelectList(@ViewBag.Traders, "TraderId", "TraderHandle"), new { @class = "form" })
    <br>

    @Html.Label("Is this a cutting?")
    @Html.CheckBox("isCutting", false, new { @class = "form" })
    <br>

    @Html.Label("Listing date")
    @Html.TextBox("listingDate", "", new { @class = "form" })
    <br>

    @Html.Label("Which plant will you accept for this?")
    @Html.DropDownList("exchangeId", new SelectList(@ViewBag.Plants, "PlantId", "CommonName"), new { @class = "form" })
    <br>

    @Html.Label("", "Which plant will you accept for this? We know it's goofy but please enter it again. Be sure to select the same plant.")
    @Html.DropDownList("exchangeCommonName", new SelectList(@ViewBag.Plants, "CommonName", "CommonName"), new { @class = "form" })
    <br>

    @Html.Label("Would you accept an imperfect match?")
    @Html.CheckBox("imperfectMatch", false, new { @class = "form" })
    <br>

    @Html.Label("What is the maximum distance in miles you are willing to travel to complete this trade?")
    @Html.TextBox("maxDistance", "", new { @class = "form" })
    <br>

    <input type="submit" class="button" value="Save" />
  }
</div

PlantSwap/Views/Plants/AddRequest.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant

<h2>Add a request for @Html.DisplayFor(model => model.CommonName)</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

<div class="form-entry">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.PlantId)

    @Html.Label("Select *your* Handle")
    @Html.DropDownList("traderId", new SelectList(@ViewBag.Traders, "TraderId", "TraderHandle"), new { @class = "form" })
    <br>

    @Html.Label("Listing Date")
    @Html.TextBox("listingDate", "", new { @class = "form" })
    <br>

    @Html.Label("What plant would you trade for this?")
    @Html.DropDownList("exchangeId", new SelectList(@ViewBag.Plants, "PlantId", "CommonName"), new { @class = "form" })
    <br>

    @Html.Label("", "What plant would you trade for this? We know it's goofy but please enter it again. Be sure to select the same plant.")
    @Html.DropDownList("exchangeCommonName", new SelectList(@ViewBag.Plants, "CommonName", "CommonName"), new { @class = "form" })
    <br>

    @Html.Label("Is this a cutting?")
    @Html.CheckBox("isCutting", false, new { @class = "form" })
    <br>

    @Html.Label("What is the max distance you are willing to travel to complete this trade?")
    @Html.TextBox("maxDistance", "", new { @class = "form" })
    <br>

    <input type="submit" class="button" value="Save" />
  }
</div>

PlantSwap/Views/Plants/Create.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant

<h4>Add a new plant</h4>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
<div class="form-entry">
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Genus)
    @Html.TextBoxFor(model => model.Genus, new { @class = "form" })
    <br>

    @Html.LabelFor(model => model.Species)
    @Html.TextBoxFor(model => model.Species, new { @class = "form" })
    <br>

    @Html.LabelFor(model => model.CommonName)
    @Html.TextBoxFor(model => model.CommonName, new { @class = "form" })
    <p><i>* Common Name is required</i></p>

    @Html.LabelFor(model => model.Variety)
    @Html.TextBoxFor(model => model.Variety, new { @class = "form" })
    <br>

    <input type="submit" class="button" value="Add new plant" />
}
</div>

PlantSwap/Views/Plants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.CommonName)?</h2>

@Html.DisplayNameFor(model => model.CommonName): @Html.DisplayFor(model => model.CommonName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="button"/>
}

PlantSwap/Views/Plants/Details.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant;

<h1>@Html.DisplayFor(model => model.CommonName)</h2>
<hr />
<h5>@Html.DisplayNameFor(model => model.CommonName): @Html.DisplayFor(model => model.CommonName)</h5>
<h5>@Html.DisplayNameFor(model => model.Genus): @Html.DisplayFor(model => model.Genus)</h5>
<h5>@Html.DisplayNameFor(model => model.Species): @Html.DisplayFor(model => model.Species)</h5>
<h5>@Html.DisplayNameFor(model => model.Variety): @Html.DisplayFor(model => model.Variety)</h5>
<hr />

<h1>Offers</h1>
@if(@Model.OfferJoinEntity.Count == 0)
{
  <h5>No offers of @Html.DisplayFor(model => model.CommonName) are currently available.</h5>
}
else
{
  @foreach(var join in Model.OfferJoinEntity)
  {
    <h5>In exchange for: @Html.ActionLink($"{@join.WillAcceptPlantCommonName}", "Details", "Plants", new { id = @join.WillAcceptPlantId }, new { @class = "link" })</h5>

    if(@join.IsCutting == true)
    {
      <p>This offer is a cutting</p>
    }

    <p>From: @Html.ActionLink($"{@join.Trader.TraderHandle}", "Details", "Traders", new { id = @join.Trader.TraderId }, new { @class = "link" })</p>

    if(@join.ImperfectMatch == true)
    {
      <p>@join.Trader.TraderHandle *will* consider other plants in exchange for their @Html.DisplayFor(model => model.CommonName)</p>
    }

    <p>Listing date: @join.ListingDate</p>
    <p>Maximum distance: @join.MaxDistance miles from zip code @join.Trader.ZipCode</p>
    @using (Html.BeginForm("DeleteOffer", "Plants"))
    {
      @Html.Hidden("joinId", @join.OfferId)
      <input type="submit" class="button" value="Delete"/>
    }
  }
}
<hr />

<h1>Requests</h1>
@if(@Model.RequestJoinEntity.Count == 0)
{
  <h5>No requests are currently made for @Html.DisplayFor(model => model.CommonName).</h5>
}
else
{
  @foreach(var join in Model.RequestJoinEntity)
  {
    <h5>In exchange for: @Html.ActionLink($"{@join.HaveToOfferPlantCommonName}", "Details", "Plants", new { id = @join.HaveToOfferPlantId }, new { @class = "link" })</h5>
    <p>From: @Html.ActionLink($"{@join.Trader.TraderHandle}", "Details", "Traders", new { id = @join.Trader.TraderId }, new { @class = "link" })</p>
    
    if(@join.IsCutting == true)
    {
      <p>This plant is a cutting</p>
    }

    <p>Listing date: @join.ListingDate</p>
    <p>Maximum distance: @join.MaxDistance miles from zip code @join.Trader.ZipCode</p>
    
    @using (Html.BeginForm("DeleteRequest", "Plants"))
    {
      @Html.Hidden("joinId", @join.RequestId)
      <input type="submit" class="button" value="Delete"/>
    }
  }
}

<hr />
<p>@Html.ActionLink("Add an Offer", "AddOffer", new { id = Model.PlantId }, new { @class = "link" })</p>
<p>@Html.ActionLink("Add a Request", "AddRequest", new { id = Model.PlantId }, new { @class = "link" })</p>
<p>@Html.ActionLink("Edit Plant", "Edit", new { id = Model.PlantId }, new { @class = "link" })</p>
<p>@Html.ActionLink("Delete Plant", "Delete", new { id = Model.PlantId }, new { @class = "link" })</p>

PlantSwap/Views/Plants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PlantSwap.Models.Plant

<h2>Edit</h2>

<h4>Edit this plant: @Html.DisplayFor(model => model.CommonName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PlantId)

    @Html.LabelFor(model => model.Genus)
    @Html.EditorFor(model => model.Genus)
    <br>
    @Html.LabelFor(model => model.Species)
    @Html.EditorFor(model => model.Species)
    <br>
    @Html.LabelFor(model => model.CommonName)
    @Html.EditorFor(model => model.CommonName)
    <br>
    @Html.LabelFor(model => model.Variety)
    @Html.EditorFor(model => model.Variety)
    <br>
    <input type="submit" value="Save" />
}

PlantSwap/Views/Plants/Index.cshtml
@{
  Layout = "_Layout";
}

@using PlantSwap.Models;
@model List<PlantSwap.Models.Plant>;

<h1>The Plants</h1>
<hr />

@if (@Model.Count == 0)
{
  <h3>No plants have been added yet!</h3>
} 

@foreach (Plant plant in Model)
{
  <p>@Html.ActionLink($"{plant.CommonName}", "Details", new { id = plant.PlantId }, new { @class = "link" })</p>
}